//SingleLineScrollView, ListView,
import 'package:flutter/material.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.amber.shade100,
        appBar: AppBar(
          title: Text("Home Screen"),
          foregroundColor: Colors.black,
          backgroundColor: Colors.amber.shade700,
          centerTitle: true,
          leading: Icon(Icons.home),
        ),
        // body: SingleChildScrollView(
        //   child: Column(
        //       children: [
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //     Text('Memorzing widget'),
        //   ] // style: TextStyle(
        //       //   fontSize: 22, fontWeight: FontWeight.bold,
        //       //   letterSpacing: 2,
        //       //   color: Colors.grey.shade700,
        //       // ),
        //       ),
        body: ListView(
          children: [
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),
            Text('Memorzing widget'),

          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          child: Icon(Icons.add_a_photo),
          backgroundColor: Colors.amber.shade700,

      ),
      ),
    );
  }
}
